# Generated by Django 4.2.7 on 2024-01-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_paystackpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackPayment',
        ),
    ]
